encoding: utf-8
title: Templates-Master docs
email: support@templates-master.com
description: > # this means to ignore newlines until "baseurl:"
  Templates-Master extensions, themes and development documentation
baseurl: ""
url: "http://tmhub.github.io"

permalink: pretty

safe: true
lsi: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - bower_components/lunr.js/example/
  - bower_components/lunr.js/lib/
  - bower_components/lunr.js/test/
  - bower_components/material-design-lite/src/
  - bower_components/material-design-lite/utils/
  - bower_components/mustache/bin/
  - bower_components/mustache/hooks/
  - bower_components/mustache/spec/
  - bower_components/mustache/wrappers/

github:
  repository_url: https://github.com/tmhub/tmhub.github.io

prose:
  siteurl: "http://tmhub.github.io/"
  media: "media"
  ignore:
    - .gitignore
    - bower.json
    - _config.yml
    - search.json
    - /_includes
    - /_layouts
    - /_posts
    - /bower_components
