- title: Extensions
  items:
    - title: Attributepages
      url: /extensions/attributepages/

    - title: Cache
      url: /extensions/cache/

    - title: Configurable Swatches
      url: /extensions/catalog-configurable-swatches/
      free: 1

    - title: Crawler
      url: /extensions/crawler/

    - title: EasyCatalogImages
      url: /extensions/easycatalogimages/
      free: 1

    - title: Email
      url: /extensions/email/

    - title: Firecheckout
      url: /extensions/firecheckout/

    - title: Navigation Pro
      url: /extensions/navigationpro/

    - title: Order Attachments
      url: /extensions/order-attachments/

    - title: Testimonials
      url: /extensions/testimonials/
      free: 1

    - title: Rich Snippets
      url: /extensions/richsnippets/

- title: Argento themes
  url: /argento/
  items:
    - title: Argento Default
      url: /argento/default/

    - title: Argento Flat
      url: /argento/flat/

    - title: Argento Mall
      url: /argento/mall/

    - title: Argento Pure
      url: /argento/pure/

    - title: Argento Pure 2
      url: /argento/pure2/

- title: Argento 2 themes
  url: /argento2/
  items:
     - title: Argento Essence
       url: /argento2/essence/

- title: Themes
  items:
    - title: Absolute Theme
      url: /themes/f001-absolute/
      free: 1

    - title: Classic Theme
      url: /themes/f002-classic/
      free: 1

    - title: Mobile Star Theme
      url: /themes/m001-mobile-star/
